import discord
import string
import random 
import time

token = "token"

now = datetime.datetime.now()
client = discord.Client()
@client.event
async def on_ready():
    print('logs: ')
	
def id_generator(size=16, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))

@client.event
async def on_message(message):
    if message.content.startswith("!crash"):
        await client.send_message(message.channel, "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n")
        time.sleep(0.2)
        await client.send_message(message.channel, "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n")
        time.sleep(0.2)
        await client.send_message(message.channel, "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n")
        time.sleep(0.2)
        await client.send_message(message.channel, "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n")
        time.sleep(0.2)
        await client.send_message(message.channel, "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n")
        time.sleep(0.2)
        await client.send_message(message.channel, "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n")
        time.sleep(0.2)
        await client.send_message(message.channel, "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n")
        time.sleep(0.2)
        await client.send_message(message.channel, "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n")
        time.sleep(0.2)
        await client.send_message(message.channel, "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n" + "https://discord.gift/" + id_generator() + "\n")
client.run(token, bot=False)
